mqtt:
  - id: 1
    type: all
    host: 127.0.0.1
    port: 1883
    user: test
    password: 123456
    clientid: cpp_ccf_202013_pub_realtime_11
    clean: true
    enable: true
    subtops:
      control:
        - topic: /hubei/+/control/#
          qos: 1
sqldb:
  enable: true
  type: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: hswry
redis:
 enable: true
 host: 127.0.0.1
 port: 6379
 password: 123456
 index: 3
 ttl: 7200
times:
  day: 0
  hour: 0
  fminute: 0
  minute: 0
  real: 10
  state: 0
  env: 0
  qc: 0
  alarm: 0
tcp:
  enable: true
  host: 127.0.0.1
  port: 8085
mbstcp:
  enable: true
  host: 127.0.0.1
  port: 6000
rpc:
  enable: true
  host: 0.0.0.0
  port: 18885
ws:
  enable: false
  host: 0.0.0.0
  port: 8088
protocol: GB212
# format: 31,32
# type: pollution
format: 51
type: oilfume
log: true